spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/nurschool # ;MVCC=TRUE 는 DB커넥션 여러개 허용하는것,, 권장옵션임
    url: jdbc:mariadb://localhost:3306/nurschool
    username: dkdkdkdk555
    password: ss2022
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true # system.out.println 해서 커맨드라인에 찍는거.. 사용 ㄴㄴ
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug # 생성 sql이 logger를 찍어서 보이도록
server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
